/**
 * Sample API
 * A sample API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Bill model module.
 * @module model/Bill
 * @version 1.0
 */
class Bill {
    /**
     * Constructs a new <code>Bill</code>.
     * @alias module:model/Bill
     * @param amount {Number} Amount
     * @param caregoryId {Number} category
     * @param userId {Number} user
     */
    constructor(amount, caregoryId, userId) { 
        
        Bill.initialize(this, amount, caregoryId, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, caregoryId, userId) { 
        obj['amount'] = amount;
        obj['caregory_id'] = caregoryId;
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>Bill</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Bill} obj Optional instance to populate.
     * @return {module:model/Bill} The populated <code>Bill</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Bill();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('caregory_id')) {
                obj['caregory_id'] = ApiClient.convertToType(data['caregory_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Amount
 * @member {Number} amount
 */
Bill.prototype['amount'] = undefined;

/**
 * category
 * @member {Number} caregory_id
 */
Bill.prototype['caregory_id'] = undefined;

/**
 * user
 * @member {Number} user_id
 */
Bill.prototype['user_id'] = undefined;

/**
 * date
 * @member {Date} date
 */
Bill.prototype['date'] = undefined;






export default Bill;

